### ISSUE TITLE
The app dont work i want it work

### ISSUE THREAD

**Issue by JorgenPo** [ArtemPopof/RehearsalApp#35]
But it is not working for me I have Nintendo switch and Gameboy and they are working so you should fix this bug

CRITICAL BUG

**Comment by JorgenPo** [comment]
FAST

**Comment by ArtemPopof** [comment]
Hello JorgenPo, thank you for showing interest in our App. Unfortunately, at this point supported platforms include only Android 4.1+, and there are no plans to add support for Nintendo Switch or Gameboy. Sorry for the inconvenience caused.

**Comment by JorgenPo** [comment]
That's sick man.
