### ISSUE TITLE
When do you plan to support C++17 features

### ISSUE THREAD

**Issue by JorgenPo** [ArtemPopof/RehearsalApp#36]
I have a question. I have a new Nintendo GameBoy Advance and it is working good but I also have Switch and it is laggy. So when do you provide support of C++17 to this project?

This is extremely important for me. Write back as soon as you can.

**Comment by JorgenPo** [comment]
SUPPORT OF C++17 LACK SUPPORT BUG LAGGY SOFT NOT WORKING PROPERLY

**Comment by ArtemPopof** [comment]
Yeah, we have C+++17 support in the future releases. Just stay tuned!
