### ISSUE TITLE
Crash on Win2K

### ISSUE THREAD

**Issue by JorgenPo** [ArtemPopof/RehearsalApp#37]
I've got a crash on Windows 2000 yesterday 

![image](https://user-images.githubusercontent.com/6198711/67521668-ffa39400-f6b3-11e9-8fc5-470a53733092.png)

**Comment by JorgenPo** [comment]
YOU HAVE SEGFAULT
It seems like INETCOMM.DLL
Can you fix that please as soon as you can

**Comment by ArtemPopof** [comment]
Update your hardware to recent iMac, best regards, Rehearsapp team.

**Comment by JorgenPo** [comment]
sharlatan
