### ISSUE TITLE
Need a way to delete an app from the app

### ISSUE THREAD

**Issue by JorgenPo** [ArtemPopof/RehearsalApp#40]
We definitely need a way to remove an app from the app. The button "delete" should be there I think.

THANKS

**Comment by JorgenPo** [comment]
It should be like this one:
![image](https://user-images.githubusercontent.com/6198711/67559431-9f4b3b80-f721-11e9-9f8a-014f7d6f6dc7.png)

**Comment by ArtemPopof** [comment]
Yeah, just go outside and take a walk man
